name: appname_kebab_case

services:
  backend:
    build:
      context: ../../
      dockerfile: deployments/dev/backend/Dockerfile
      tags:
        - "appname_kebab_case-backend:dev"
    container_name: appname_kebab_case-backend
    volumes:
      - ../..:/app
      - backend-data:/run/app
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      JWT_SECRET: super-secret-jwt-secret
      POSTGRES_URL: postgresql+psycopg://root:root@postgres/root
    command: appname_kebab_case-web-service
    healthcheck:
      test: wget backend:8000/healthcheck -q -O /dev/null
      start_period: 1m
      start_interval: 1s
      interval: 5s

  postgres:
    image: postgres:16.3-alpine3.19
    container_name: appname_kebab_case-postgres
    labels:
      deployment: dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: pg_isready -d root -U root
      start_period: 1m
      start_interval: 1s
      interval: 5s

volumes:
  backend-data: null

  postgres-data:
    labels:
      db: true
