"""clarify unit column names

Revision ID: 8f2f49f85ccc
Revises: 941ec19e9efd
Create Date: 2025-03-20 09:15:25.115948

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "8f2f49f85ccc"
down_revision: str | None = "941ec19e9efd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "crusts",
        sa.Column("thickness_millimeters_number", sa.Integer(), nullable=False),
    )
    op.add_column(
        "crusts",
        sa.Column("diameter_millimeters_number", sa.Integer(), nullable=False),
    )
    op.drop_column("crusts", "diameter")
    op.drop_column("crusts", "thickness")
    op.add_column(
        "ingredients", sa.Column("grams_number", sa.Integer(), nullable=False)
    )
    op.drop_column("ingredients", "grams")
    op.add_column(
        "sauces", sa.Column("milliliters_number", sa.Integer(), nullable=False)
    )
    op.drop_column("sauces", "milliliters")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sauces",
        sa.Column(
            "milliliters", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("sauces", "milliliters_number")
    op.add_column(
        "ingredients",
        sa.Column("grams", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("ingredients", "grams_number")
    op.add_column(
        "crusts",
        sa.Column(
            "thickness", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "crusts",
        sa.Column(
            "diameter", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("crusts", "diameter_millimeters_number")
    op.drop_column("crusts", "thickness_millimeters_number")
    # ### end Alembic commands ###
