"""add tables for entities

Revision ID: 941ec19e9efd
Revises:
Create Date: 2025-03-19 22:20:48.317597

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "941ec19e9efd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "mozzarella",
        "parmesan",
        "ricotta",
        "gorgonzola",
        "cheddar",
        "feta",
        "provolone",
        "burrata",
        "brie",
        "goat_cheese",
        "vegan_cheese",
        "pepperoni",
        "ham",
        "bacon",
        "sausage",
        "chorizo",
        "salami",
        "grilled_chicken",
        "prosciutto",
        "ground_beef",
        "calabrese_sausage",
        "anchovies",
        "shrimp",
        "smoked_salmon",
        "tuna",
        "seaweed",
        "mushrooms",
        "bell_peppers",
        "red_onion",
        "black_olives",
        "jalape_os",
        "spinach",
        "artichokes",
        "arugula",
        "sun_dried_tomatoes",
        "cherry_tomatoes",
        "zucchini",
        "eggplant",
        "broccoli",
        "capers",
        "basil",
        "garlic",
        "pineapple",
        "corn",
        "potato_slices",
        "asparagus",
        name="ingredient_name",
    ).create(op.get_bind())
    sa.Enum(
        "tomato_sauce",
        "marinara_sauce",
        "pesto_sauce",
        "alfredo_sauce",
        "bbq_sauce",
        "garlic_sauce",
        "truffle_oil",
        "salsa",
        "mayo",
        "ketchup",
        name="sauce_name",
    ).create(op.get_bind())
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pizzas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crusts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pizza_id", sa.Uuid(), nullable=False),
        sa.Column("thickness", sa.Integer(), nullable=False),
        sa.Column("diameter", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pizza_id"],
            ["pizzas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pizza_id", sa.Uuid(), nullable=False),
        sa.Column(
            "name",
            postgresql.ENUM(
                "mozzarella",
                "parmesan",
                "ricotta",
                "gorgonzola",
                "cheddar",
                "feta",
                "provolone",
                "burrata",
                "brie",
                "goat_cheese",
                "vegan_cheese",
                "pepperoni",
                "ham",
                "bacon",
                "sausage",
                "chorizo",
                "salami",
                "grilled_chicken",
                "prosciutto",
                "ground_beef",
                "calabrese_sausage",
                "anchovies",
                "shrimp",
                "smoked_salmon",
                "tuna",
                "seaweed",
                "mushrooms",
                "bell_peppers",
                "red_onion",
                "black_olives",
                "jalape_os",
                "spinach",
                "artichokes",
                "arugula",
                "sun_dried_tomatoes",
                "cherry_tomatoes",
                "zucchini",
                "eggplant",
                "broccoli",
                "capers",
                "basil",
                "garlic",
                "pineapple",
                "corn",
                "potato_slices",
                "asparagus",
                name="ingredient_name",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("grams", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pizza_id"],
            ["pizzas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sauces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pizza_id", sa.Uuid(), nullable=False),
        sa.Column(
            "name",
            postgresql.ENUM(
                "tomato_sauce",
                "marinara_sauce",
                "pesto_sauce",
                "alfredo_sauce",
                "bbq_sauce",
                "garlic_sauce",
                "truffle_oil",
                "salsa",
                "mayo",
                "ketchup",
                name="sauce_name",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("milliliters", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pizza_id"],
            ["pizzas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sauces")
    op.drop_table("ingredients")
    op.drop_table("crusts")
    op.drop_table("pizzas")
    op.drop_table("users")
    sa.Enum(
        "tomato_sauce",
        "marinara_sauce",
        "pesto_sauce",
        "alfredo_sauce",
        "bbq_sauce",
        "garlic_sauce",
        "truffle_oil",
        "salsa",
        "mayo",
        "ketchup",
        name="sauce_name",
    ).drop(op.get_bind())
    sa.Enum(
        "mozzarella",
        "parmesan",
        "ricotta",
        "gorgonzola",
        "cheddar",
        "feta",
        "provolone",
        "burrata",
        "brie",
        "goat_cheese",
        "vegan_cheese",
        "pepperoni",
        "ham",
        "bacon",
        "sausage",
        "chorizo",
        "salami",
        "grilled_chicken",
        "prosciutto",
        "ground_beef",
        "calabrese_sausage",
        "anchovies",
        "shrimp",
        "smoked_salmon",
        "tuna",
        "seaweed",
        "mushrooms",
        "bell_peppers",
        "red_onion",
        "black_olives",
        "jalape_os",
        "spinach",
        "artichokes",
        "arugula",
        "sun_dried_tomatoes",
        "cherry_tomatoes",
        "zucchini",
        "eggplant",
        "broccoli",
        "capers",
        "basil",
        "garlic",
        "pineapple",
        "corn",
        "potato_slices",
        "asparagus",
        name="ingredient_name",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
