name: CI

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff
        run: docker compose -f deployments/dev/docker-compose.yaml run backend ruff check src tests

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mypy
        run: docker compose -f deployments/dev/docker-compose.yaml run backend mypy src tests

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pytest
        run: docker compose -f deployments/dev/docker-compose.yaml run backend pytest tests --cov --cov-report=xml

      - name: upload coverage reports to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
